name: RegionMusic
version: '1.9'
main: org.rynx.regionMusic.RegionMusic
api-version: '1.21'
author: rynx
depend: [WorldGuard]
commands:
  regionmusic:
    description: Lệnh quản trị RegionMusic
    usage: /regionmusic <reload|playmusic|stopmusic|togglemusic|nextsong|about|gui|addmusic>
    aliases: [rm]
  togglemusic:
    description: Bật/tắt nhạc
    usage: /togglemusic
    aliases: []
  cancel:
    description: Hủy thêm bài hát
    usage: /cancel
    aliases: []
permissions:
  regionmusic.admin:
    description: Cho phép truy cập tất cả các lệnh RegionMusic (parent permission)
    default: op
    children:
      regionmusic.reload: true
      regionmusic.playmusic: true
      regionmusic.stopmusic: true
      regionmusic.togglemusic: true
      regionmusic.nextsong: true
      regionmusic.about: true
  regionmusic.reload:
    description: Cho phép sử dụng lệnh /regionmusic reload
    default: op
  regionmusic.playmusic:
    description: Cho phép sử dụng lệnh /regionmusic playmusic
    default: op
  regionmusic.stopmusic:
    description: Cho phép sử dụng lệnh /regionmusic stopmusic
    default: op
  regionmusic.togglemusic:
    description: Cho phép sử dụng lệnh /regionmusic togglemusic
    default: op
  regionmusic.nextsong:
    description: Cho phép sử dụng lệnh /regionmusic nextsong
    default: op
  regionmusic.about:
    description: Cho phép sử dụng lệnh /regionmusic about
    default: op
