name: RegionMusic
version: '1.4'
main: org.rynx.regionMusic.RegionMusic
api-version: '1.21'
author: rynx
depend: [WorldGuard]
commands:
  regionmusic:
    description: Lệnh quản trị RegionMusic
    usage: /regionmusic <reload|playmusic|stopmusic|togglemusic|nextsong|about>
    aliases: [rm]
  togglemusic:
    description: Bật/tắt nhạc
    usage: /togglemusic
    aliases: []
permissions:
  regionmusic.admin:
    description: Cho phép truy cập các lệnh RegionMusic
    default: op
